### ISSUE TITLE
Unable to download quanteda/quanteda.corpora

### ISSUE THREAD

**Issue by pgetty** [quanteda/quanteda.corpora#13]
Hello! I'm new to text analysis and going through the tutorial at https://tutorials.quanteda.io.

I tried to download quanteda/quanteda.corpora with the recommended code: devtools::install_github("quanteda/quanteda.corpora"). 

Unfortunately, I got an error message back: 
> devtools::install_github("quanteda/quanteda.corpora")
Downloading GitHub repo quanteda/quanteda.corpora@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/quanteda/quanteda.corpora/tarball/HEAD'

Any recommendations? 

Thank you!

Phil

**Comment by kbenoit** [comment]
Only to try again. It just worked for me.

You can also try:

```r
remotes::install_github("quanteda/quanteda.corpora")
```

**Comment by pgetty** [comment]
Right on. Thank you!
